//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mgmtapplauncher2.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mgmtapplauncher2.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string ButtonQuit {
            get {
                return ResourceManager.GetString("ButtonQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files|*.exe.
        /// </summary>
        public static string FilterExecutableFiles {
            get {
                return ResourceManager.GetString("FilterExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol settings.
        /// </summary>
        public static string GroupProtocolSettings {
            get {
                return ResourceManager.GetString("GroupProtocolSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application:.
        /// </summary>
        public static string LabelApplication {
            get {
                return ResourceManager.GetString("LabelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Michał Kępień.
        /// </summary>
        public static string LabelAuthor {
            get {
                return ResourceManager.GetString("LabelAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter protocol name:.
        /// </summary>
        public static string LabelEnterProtocolName {
            get {
                return ResourceManager.GetString("LabelEnterProtocolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler:.
        /// </summary>
        public static string LabelHandler {
            get {
                return ResourceManager.GetString("LabelHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters:.
        /// </summary>
        public static string LabelParameters {
            get {
                return ResourceManager.GetString("LabelParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %P% - protocol, %H% - host.
        /// </summary>
        public static string LabelParametersTip {
            get {
                return ResourceManager.GetString("LabelParametersTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol:.
        /// </summary>
        public static string LabelProtocol {
            get {
                return ResourceManager.GetString("LabelProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing configuration file {0}!.
        /// </summary>
        public static string MessageConfigCorrupt {
            get {
                return ResourceManager.GetString("MessageConfigCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file not found. Would you like to use default settings?.
        /// </summary>
        public static string MessageConfigNotFound {
            get {
                return ResourceManager.GetString("MessageConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol name cannot be empty!.
        /// </summary>
        public static string MessageEmptyProtocolName {
            get {
                return ResourceManager.GetString("MessageEmptyProtocolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start program &quot;{0}&quot;!.
        /// </summary>
        public static string MessageFailedToStartProgram {
            get {
                return ResourceManager.GetString("MessageFailedToStartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect URI format!.
        /// </summary>
        public static string MessageIncorrectURIFormat {
            get {
                return ResourceManager.GetString("MessageIncorrectURIFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol &quot;{0}&quot; has no application set!.
        /// </summary>
        public static string MessageNoProtocolApp {
            get {
                return ResourceManager.GetString("MessageNoProtocolApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol &quot;{0}&quot; is not supported!.
        /// </summary>
        public static string MessageProtocolNotSupported {
            get {
                return ResourceManager.GetString("MessageProtocolNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings to {0}!.
        /// </summary>
        public static string MessageSettingsNotSaved {
            get {
                return ResourceManager.GetString("MessageSettingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved!.
        /// </summary>
        public static string MessageSettingsSaved {
            get {
                return ResourceManager.GetString("MessageSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TitleAboutWindow {
            get {
                return ResourceManager.GetString("TitleAboutWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management applications configuration.
        /// </summary>
        public static string TitleMainWindow {
            get {
                return ResourceManager.GetString("TitleMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string TitleProtocolNameWindow {
            get {
                return ResourceManager.GetString("TitleProtocolNameWindow", resourceCulture);
            }
        }
    }
}
