//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mgmtapplauncher2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mgmtapplauncher2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Protocols xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Protocol&gt;
        ///    &lt;Name&gt;rdp&lt;/Name&gt;
        ///    &lt;App&gt;C:\WINDOWS\SYSTEM32\mstsc.exe&lt;/App&gt;
        ///    &lt;Args&gt;/v:%H%&lt;/Args&gt;
        ///  &lt;/Protocol&gt;
        ///  &lt;Protocol&gt;
        ///    &lt;Name&gt;ssh&lt;/Name&gt;
        ///    &lt;App&gt;C:\putty.exe&lt;/App&gt;
        ///    &lt;Args&gt;-%P% %H%&lt;/Args&gt;
        ///  &lt;/Protocol&gt;
        ///  &lt;Protocol&gt;
        ///    &lt;Name&gt;telnet&lt;/Name&gt;
        ///    &lt;App&gt;C:\putty.exe&lt;/App&gt;
        ///    &lt;Args&gt;-%P% %H%&lt;/Args&gt;
        ///  &lt;/Protocol&gt;
        ///&lt;/Protocols&gt;.
        /// </summary>
        internal static string DefaultConfig {
            get {
                return ResourceManager.GetString("DefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d61f4825019ddcbf1c0d4785ae67568d14e22759
        ///.
        /// </summary>
        internal static string GitCommit {
            get {
                return ResourceManager.GetString("GitCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon mgmtapplauncher2 {
            get {
                object obj = ResourceManager.GetObject("mgmtapplauncher2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
